services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUTH_SECRET: ${AUTH_SECRET}
        NEXTAUTH_URL: ${AUTH_URL}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL_MONGODB=${DATABASE_URL_MONGODB}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.production
